# Site settings
title: moon
email: hymcn2008@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hymcn.github.io/hymcn" # the base hostname & protocol for your site
twitter_username: hymcn
github_username:  hymcn

# Build settings
markdown: kramdown
